#!/usr/bin/perl
#
# @file: svnaccess
# @brief: svn access perl script
# @author: YoungJoo.Kim <vozlt@vozlt.com>
# @version: $Revision:
# @date: $Date:
#

my $repos = $ARGV[0];
my $user = $ARGV[1];
my $perm = $ARGV[2];

if (!$repos || !$user || !$perm)  {
	print "Usage: $0 [REPOSITORY] [USER] [R|RW]\n";
	print "\tex) $0 /svndev/NL vozlt R\n";
	exit(1);
}

my $ACCESS = Access::new();

$ACCESS->Controller();

# Package Start
package Access;

use strict;
use Fcntl;
use IO::Handle;
use File::Basename;
use DBI;

use vars qw(%groups @users %perms @passwd @group);
use vars qw($SUCCESS $FAIL @RESULTS);

sub new{

	my $self = {};

	$self->{access_repos_path} = '/home/httpd/html/websvn/repository';
	$self->{hostname} =`/bin/hostname`; chomp $self->{hostname};

	# DBI
	$self->{access_db_host} = '@db_host@';
	$self->{access_db_port} = @db_port@;
	$self->{access_db_name} = '@db_name@';
	$self->{access_db_user} = '@db_user@';
	$self->{access_db_password} = '@db_password@';
	$self->{n_rows} = undef;
	$self->{n_fields} = undef;
	$self->{dbh} = undef;
	$self->{sth} = undef;

	$self->{result} = undef;

	$SUCCESS = 0;
	$FAIL = 1;

	$RESULTS[$SUCCESS] = 'ALLOW';
	$RESULTS[$FAIL] = 'DENY';

	# See :  subversion/libsvn_ra_svn/protocol
	#        subversion/svnserve/serve.c
	#       
	# Checkout Permission
	# svn checkout/update = reparent,get-latest-rev,check-path,update
	# svn list = stat,get-dir,get-locks
	$perms{'R'} = 'reparent,get-latest-rev,check-path,update,stat,get-dir,get-locks,log,get-locations,get-file,get-file-revs,diff';
	
	# All Permission
	$perms{'RW'} = '*';

	return bless $self;
}

sub accessCreateSvn {
	my $self = shift if ref ($_[0]);
	my $query = undef;
	my $ref = undef;
	my $ret = $SUCCESS;

	if ( ! -d $repos ) {
		print "ERROR : $repos is not exist!";
		exit(1);
	}
	if (!$perms{$perm}) {
		print "ERROR : $perm is not defined! Only [R|RW]\n";
		exit(1);
	}

	$self->dbConnect($self->{access_db_host}, $self->{access_db_port}, $self->{access_db_name}, $self->{access_db_user}, $self->{access_db_password});
	$query = "SELECT * FROM svn_conf WHERE hostname='$self->{hostname}' AND repos='$repos' AND cmdname='$perms{$perm}' AND user='$user';";
	$self->dbQuery($query);
	$ref = $self->dbFetch();
	$self->dbFetchfinish();

	if ($ref->{access} eq "ALLOW") {
		print "Already SVN Permission is exist : $self->{hostname}, $repos, $perm, $user, $ref->{access}\n";
		exit(1);
	}
	if (! $ref->{access}) {
		$query = "INSERT INTO svn_conf VALUES(NULL, '$self->{hostname}', '$repos', '$perms{$perm}', NULL, '$user', 'ALLOW');";
		$self->dbQuery($query);
		print "SVN Permission Insert OK : $self->{hostname}, $repos, $perm, $user\n";
	}
	if ($ref->{access} eq "DENY") {
		$query = "UPDATE svn_conf SET access='ALLOW' WHERE hostname='$self->{hostname}' AND repos='$repos' AND cmdname='$perms{$perm}' AND user='$user';";
		$self->dbQuery($query);
		print "SVN Permission Update OK : $self->{hostname}, $repos, $perm, $user\n";
	}
	$self->dbClose();
}

sub accessCreateWsvn {
	my $self = shift if ref ($_[0]);
	my $query = undef;
	my $ref = undef;
	my $ret = $SUCCESS;

	$self->dbConnect($self->{access_db_host}, $self->{access_db_port}, $self->{access_db_name}, $self->{access_db_user}, $self->{access_db_password});
	$query = "SELECT * FROM svn_conf WHERE hostname='$self->{hostname}' AND access='ALLOW';";

	$self->dbQuery($query);

	while ($ref = $self->dbFetch()) {
		my $repos = basename($ref->{repos});
		if ( ! -d "$self->{access_repos_path}/$ref->{user}" ) {
			mkdir("$self->{access_repos_path}/$ref->{user}");
		}
		if ( ! -e "$self->{access_repos_path}/$ref->{user}/$repos" ) {
			symlink($ref->{repos}, "$self->{access_repos_path}/$ref->{user}/$repos");
			print "WEBSVN Permission Insert OK : $self->{hostname}, $ref->{repos}, $ref->{user}\n";
		}
	}

	$self->dbFetchfinish();
	$self->dbClose();
}

sub Controller {
	my $self = shift if ref ($_[0]);

	if ( ! -d $self->{access_repos_path} ) {
		mkdir($self->{access_repos_path});
	}
	$self->accessCreateSvn();
	$self->accessCreateWsvn();
}

sub trim {
	my $self = shift if ref ($_[0]);
	my $_r = $_[0];

	$_r =~ s/[\s\n]*//g;

	return $_r;
}

sub fileReadlines { 
	my $self = shift if ref ($_[0]);
	my $path = $_[0];
	my $ret = undef;
	my @lines = ();  
	$ret = sysopen(FH, $path, O_RDONLY);
	@lines = FH->getlines() if ($ret);
	close(FH);      
	return ($ret) ? @lines : $ret;
}

#######################################
# DBI_MYSQL
#######################################
sub dbConnect {
	my $self = shift if ref ($_[0]);
	my $access_db_host = $_[0];
	my $access_db_port = $_[1];
	my $access_db_name = $_[2];
	my $access_db_user = $_[3];
	my $access_db_password = $_[4];

	$self->{dbh} = DBI->connect("DBI:mysql:database=$access_db_name;host=$access_db_host;port=$access_db_port", $access_db_user, $access_db_password);
}

sub dbQuery {
	my $self = shift if ref ($_[0]);
	my $query = $_[0];
	$self->{sth} = $self->{dbh}->prepare($query);
	$self->{sth}->execute;
	$self->{n_rows} = $self->{sth}->rows();
	$self->{n_fields} = $self->{sth}->{'NUM_OF_FIELDS'};
}

sub dbFetch {
	my $self = shift if ref ($_[0]);
	my $sfh =  $self->{sth}->fetchrow_hashref();
	$self->{sth}->finish() if (!$sfh);
	return $sfh;
}

sub dbFetchfinish {
	my $self = shift if ref ($_[0]);
	$self->{sth}->finish();
}

sub dbClose {
	my $self = shift if ref ($_[0]);
	#$self->{sth}->finish();
	$self->{dbh}->disconnect();
}

1;
